name: publish-puff-window

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm install
          npm run lib:puff-window
      - name: Publish sub-package
        working-directory: ./packages/puff-window
        run: |
          ls
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
